# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
OR

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [6]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [7]:
# Method 1:
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [8]:
# Method 2:
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
# Method 3:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [18]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)


In [19]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
# Method 1:
np.concatenate([a, b], axis=1)


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [16]:
# Method 2:
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [17]:
# Method 3:
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [22]:
import numpy as np 
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [23]:
arr1

array([0, 1, 2])

In [24]:
arr2

array([3, 4, 5, 6])

In [25]:
arr3

array([7, 8, 9])

In [26]:
array_of_arrays = np.array([arr1, arr2, arr3])
print('array_of_arrays: ', array_of_arrays)

array_of_arrays:  [array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]


In [27]:
arr_2d = np.concatenate(array_of_arrays)
print(arr_2d)

[0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [2]:
import numpy as np
arr1 = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11],[12,13,14]])
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [8]:
arr1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
# or 
arr1.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [85]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [86]:
arr.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [28]:
x = np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Question:8

### Create 5x6 an array and find the mean?

In [38]:
arr = np.random.randn(5, 6)

arr

array([[-1.15275869, -0.28260709, -0.93219295, -1.14930655, -0.62426713,
         0.3092982 ],
       [ 0.12945953, -0.67892478, -2.66105807,  1.02440429,  0.46901852,
         0.5615647 ],
       [ 1.32064895, -1.07076563, -0.09232608, -0.6369473 ,  1.0782956 ,
         0.22913828],
       [-1.83932914,  1.00379921,  0.18490119,  1.34810432, -0.75196949,
         0.12368352],
       [ 0.3173311 , -0.37181212, -1.2297013 , -0.28550298, -0.78176835,
        -0.60049789]])

In [41]:
arr.mean()

-0.23473627079773685

In [43]:
# or
np.mean(arr)

-0.23473627079773685

In [13]:
# or
arr1 = np.arange(1,31).reshape(5,6)
arr1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [15]:
arr1.mean()

15.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [100]:
arr = np.random.randn(5, 6)
arr


array([[ 0.61058322,  0.0552602 ,  0.51972137,  0.15423478, -1.29062224,
         1.28755866],
       [-1.73509099,  0.47760481, -0.29625507, -0.16964009,  0.12933819,
        -0.212592  ],
       [-0.48618792,  0.81860595,  1.7700015 , -1.0647524 , -1.55986578,
        -0.3015862 ],
       [ 1.43932912,  0.42906496, -0.82705338,  1.39777668, -0.65279497,
         1.35463799],
       [ 0.23995612, -0.27049156,  0.24575164, -1.47114827,  1.55306673,
         0.15228962]])

In [101]:
np.std(arr)

0.9465229266759538

In [16]:
# or
arr1 = np.arange(1,31).reshape(5,6)
arr1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [17]:
np.std(arr1)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [96]:
arr = np.random.randn(5, 6)
arr

array([[-1.58666708,  1.08793828, -0.31516773,  0.15879415, -1.6965891 ,
        -0.78731897],
       [-0.10103509,  0.89758076, -0.18723499,  0.42162277,  0.98233844,
         0.31436653],
       [-1.71412523, -1.04510658,  1.7840402 , -0.38976546,  1.75467901,
        -0.46494044],
       [ 0.8599426 ,  2.19801429, -1.12221497, -1.14325047, -1.08790432,
         0.06626647],
       [ 2.31339472,  0.66670884,  1.60497076, -0.27259502, -1.46262012,
        -1.85148883]])

In [97]:
np.median(arr)

-0.14413504248390097

In [22]:
# or
arr1 = np.arange(1,31).reshape(5,6)
arr1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [23]:
np.median(arr1)

15.5

## Question:11

### Find the transpose of the previous array in Q8?

In [92]:
arr = np.random.randn(5, 6)

arr

array([[-1.64532204,  1.32333371, -0.38716473, -1.81358399, -0.76220876,
         2.31864082],
       [-0.72009411,  0.23187385, -0.17073311,  0.56152567, -1.74896814,
         0.01096234],
       [ 1.16360929,  1.1036552 ,  0.25671892,  0.12637945,  0.17762014,
        -0.14982223],
       [-0.74200187,  0.99714629,  1.8801409 , -1.34743121,  1.77230579,
        -0.80357773],
       [ 0.97892726, -1.18620027, -1.39370305,  0.04697459, -1.94303792,
         1.50306576]])

In [95]:
np.transpose(arr)



array([[-1.64532204, -0.72009411,  1.16360929, -0.74200187,  0.97892726],
       [ 1.32333371,  0.23187385,  1.1036552 ,  0.99714629, -1.18620027],
       [-0.38716473, -0.17073311,  0.25671892,  1.8801409 , -1.39370305],
       [-1.81358399,  0.56152567,  0.12637945, -1.34743121,  0.04697459],
       [-0.76220876, -1.74896814,  0.17762014,  1.77230579, -1.94303792],
       [ 2.31864082,  0.01096234, -0.14982223, -0.80357773,  1.50306576]])

In [24]:
# or
arr1 = np.arange(1,31).reshape(5,6)
arr1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [25]:
np.transpose(arr1)

array([[ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29],
       [ 6, 12, 18, 24, 30]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [49]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [50]:
arr1 = np.diag(arr)
arr1

array([ 1,  6, 11, 16])

In [51]:
arr1.sum()

34

In [52]:
np.sum(arr1)

34

## Question:13

### Find the determinant of the previous array in Q12?

In [24]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [25]:
arr1 = np.linalg.det(arr)
arr1

4.7331654313261276e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [64]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
np.percentile(arr,5)

0.45

In [67]:
np.percentile(arr,95)

8.549999999999999

## Question:15

### How to find if a given array has any null values?

In [122]:
import numpy as np
Z = np.random.randint(0,3,(3,10))
Z


array([[2, 1, 2, 0, 2, 1, 1, 1, 0, 2],
       [0, 2, 0, 2, 2, 0, 2, 2, 0, 0],
       [2, 2, 2, 0, 2, 0, 0, 2, 1, 1]])

In [123]:
Z.any()

True