# **Assignment 1 For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [292]:
import numpy as np

2. Create a null vector of size 10 

In [1]:
import numpy as np
a = np. zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [2]:
import numpy as np
z = np.arange(10,50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [4]:
import numpy as np
z = np.arange(10,50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [288]:
z.shape


(40,)

5. Print the type of the previous array in question 3

In [5]:
import numpy as np
z = np.arange(10,50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [286]:
z.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [5]:
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

7. Print the dimension of the array in question 3


In [6]:
import numpy as np
z = np.arange(10,50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [7]:
z.ndim

1

8. Create a boolean array with all the True values

In [7]:
import numpy as np 
a= np.array([1,3,11,5,9,7,])    
a

array([ 1,  3, 11,  5,  9,  7])

In [9]:
print(a[a>5])

[11  9  7]


# OR

In [4]:
arr = np.array([[1, 2, 1], [4, 3, 6]])
arr

array([[1, 2, 1],
       [4, 3, 6]])

In [5]:
arr2 = np.array([[2, 4, 8], [7, 5, 12]])
arr2

array([[ 2,  4,  8],
       [ 7,  5, 12]])

In [6]:
y= arr2 > arr
y


array([[ True,  True,  True],
       [ True,  True,  True]])

In [7]:
y.dtype

dtype('bool')

9. Create a two dimensional array




In [8]:
import numpy as np
a = np.array([[10,20,30],[40,50,60],[70,80,90]])
a


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [9]:
a.ndim

2

10. Create a three dimensional array



In [10]:
import numpy as np
x = np.array([[[10,20,30],[40,50,60],[50,30,85],[70,80,90]]])
x


array([[[10, 20, 30],
        [40, 50, 60],
        [50, 30, 85],
        [70, 80, 90]]])

In [11]:
x.ndim

3

In [8]:
import numpy as np
a = np.array([[[10,20,30,40,50],[60,70,80,90,100],[110,120,130,140,150]]])
a


array([[[ 10,  20,  30,  40,  50],
        [ 60,  70,  80,  90, 100],
        [110, 120, 130, 140, 150]]])

In [9]:
a.ndim

3

In [ ]:
or

In [15]:
import numpy as np
b = np.array([[[10,20,30,40,50],[60,70,80,90,100],[110,120,130,140,150],[160,170,180,190,200]]])
b


array([[[ 10,  20,  30,  40,  50],
        [ 60,  70,  80,  90, 100],
        [110, 120, 130, 140, 150],
        [160, 170, 180, 190, 200]]])

In [16]:
b.ndim

3

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [271]:
import numpy as np
Z = np.arange(40)
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [272]:
Z = Z[::-1]

In [273]:
Z

array([39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23,
       22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,
        5,  4,  3,  2,  1,  0])

12. Create a null vector of size 10 but the fifth value which is 1 

In [17]:
y = np.zeros(10)
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
y[4] = 1
y

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [20]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [263]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])


In [264]:
arr

array([1, 2, 3, 4, 5])

In [265]:
arr.dtype

dtype('int32')

In [21]:
arr1 = arr.astype('float64')
# arr1 = arr.sttype(np.float64)



In [22]:
arr1

array([[1., 2., 1.],
       [4., 3., 6.]])

In [23]:
arr1.dtype

dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [259]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])


In [256]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [257]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [258]:
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [243]:
arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])

       

In [244]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [245]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [252]:
arr3 = arr1 == arr2
arr3

array([[False, False, False],
       [False, False, False]])

In [ ]:
or

In [249]:
arr3 = np.intersect1d(arr1,arr2)
arr3

array([1., 2., 4.])

In [ ]:
or

In [251]:
arr3 = np.in1d(arr1,arr2)
arr3

array([ True,  True, False,  True, False, False])

17. Extract all odd numbers from arr with values(0-9)

In [89]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [91]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
arr[arr % 2 == 1] = -1
arr


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [32]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [39]:
z = np.ones((5,5))
z

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
z[1:-1,1:-1] = 0
z

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

# Replace the value 5 to 12

In [82]:
arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
arr2d[1, 1] = 12
arr2d


array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [85]:
# or
arr2d[1][1] = 12
arr2d


array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [86]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [88]:
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [95]:
arr2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
# or
arr2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [96]:
arr2d[0]

array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [241]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
arr1[1:,:-2]

array([[4.]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [95]:
arr2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [59]:
arr2d[:2, 0:]


array([[2],
       [5]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [234]:
Z = np.random.random((10,10))
Z

array([[0.5226568 , 0.7000477 , 0.85878748, 0.6873775 , 0.66314741,
        0.08326854, 0.23962118, 0.10782178, 0.85143132, 0.63105248],
       [0.27771204, 0.33012234, 0.39859437, 0.99630391, 0.57925851,
        0.78216873, 0.60158062, 0.91180547, 0.90955854, 0.96086749],
       [0.92163896, 0.63009068, 0.98063149, 0.75333989, 0.45804106,
        0.21999576, 0.70132914, 0.36505094, 0.3670762 , 0.47960704],
       [0.75121937, 0.98995627, 0.68512734, 0.80373254, 0.33185492,
        0.56624125, 0.93290234, 0.76601101, 0.71637056, 0.67180799],
       [0.78422564, 0.74362094, 0.05611961, 0.05236711, 0.58005956,
        0.36287349, 0.29040673, 0.78200565, 0.66367305, 0.08011568],
       [0.72523788, 0.05715118, 0.42778618, 0.49591809, 0.9302178 ,
        0.66744332, 0.97969039, 0.92617577, 0.73689893, 0.14855983],
       [0.23849429, 0.34099748, 0.69944416, 0.6300852 , 0.31898638,
        0.58664866, 0.27039042, 0.6197166 , 0.81639882, 0.13341626],
       [0.85768811, 0.94793938, 0.2595269

In [235]:
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0028010984984815357 0.996303905618121


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [10]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [11]:
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [12]:
b

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [17]:
np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [13]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])


In [14]:
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [15]:
b

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [16]:
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [218]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)



In [219]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [220]:
data 

array([[ 0.22317959, -0.12106132,  0.23674318,  0.49886916],
       [ 0.43459965,  0.47942102, -0.80181476,  0.70216278],
       [-1.06472443,  0.60252079, -0.52109451, -0.4794297 ],
       [ 0.68919038, -1.0312017 ,  1.1113268 ,  1.19244612],
       [ 0.07562194, -1.50623713, -0.21708808, -0.28651392],
       [ 1.04200693,  0.3837371 , -0.0495568 , -0.3404244 ],
       [-1.17960341,  1.07164191, -0.75704143, -0.15990347]])

In [221]:
data[names != 'Will'] = 7
data


array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [-1.06472443,  0.60252079, -0.52109451, -0.4794297 ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.07562194, -1.50623713, -0.21708808, -0.28651392],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ]])

In [226]:
data[names != 'Joe'] = 7
data


array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [137]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(names,data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe'] [[-1.80036888  1.28447744 -0.91221697 -0.31052731]
 [ 1.10680231  0.02935417  0.77106332 -1.09278496]
 [ 0.67718514  1.24899881 -0.96805323  0.88685991]
 [ 0.95201475 -0.02051916  0.61992563  1.35635438]
 [ 1.12341969 -1.02335478  1.15830646 -2.15954392]
 [ 0.20764394  0.88772614 -1.73629423 -0.49783679]
 [-0.54706093  1.12547441  1.57391625 -1.59637958]]


In [132]:
names != 'Joe'

array([ True, False,  True,  True,  True, False, False])

In [227]:
names != 'Will'

array([ True,  True, False,  True, False,  True,  True])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [20]:
import numpy as np
a = np.arange(15).reshape(5,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
or

In [21]:
arr = np.arange(15).reshape(5,3)
arr = np.random.uniform(1,16, size=(5,3))
print(arr)


[[ 1.4226448   6.22291417 10.92603705]
 [ 1.15926735 12.79974773 14.68444074]
 [12.32517612 10.42993119  8.54915658]
 [13.0326891   3.21370884  8.96872434]
 [15.25288235 12.36971286 14.65937905]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [34]:
import numpy as np 
x = np.arange(1,17).reshape(2,2,4)
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [65]:
import numpy as np 
x = np.arange(1,17).reshape(2,2,4)
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [69]:
x[[0,1]] = x[[1,0]]
x

array([[[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]]])

In [70]:
#or
x[[0,1], :-2]
x

array([[[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]]])

In [71]:
#or
x.swapaxes(1, 2)
x

array([[[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [199]:
arr = np.arange(10)

In [200]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [201]:
np.sqrt(arr)


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [176]:
x = np.random.randn(12)
y = np.random.randn(12)

In [177]:
x

array([-1.39614597,  0.18153195,  1.45067791, -0.08715963, -1.19480317,
       -0.88478665, -0.38923941,  0.50057454,  0.46036338, -1.33175601,
       -0.5765276 , -3.38935206])

In [178]:
y

array([ 0.57581955,  0.48515764, -0.25320706, -0.18839038, -0.16898909,
        0.5111269 ,  2.99065388,  0.23278392, -0.02833039, -0.56595286,
        0.89098075,  1.00031243])

In [179]:
np.maximum(x, y)

array([ 0.57581955,  0.48515764,  1.45067791, -0.08715963, -0.16898909,
        0.5111269 ,  2.99065388,  0.50057454,  0.46036338, -0.56595286,
        0.89098075,  1.00031243])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [172]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [173]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [72]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(a,b)

[1 2 3 4 5] [5 6 7 8 9]


In [171]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [136]:
import numpy as np
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [152]:
np.delete(sampleArray, 2,1)

array([[34, 43],
       [82, 22],
       [53, 94]])

In [144]:
newColumn = np.array([[10,10,10]])
newColumn
                       

array([[10, 10, 10]])

In [167]:
np.insert(sampleArray, 2, 10, axis = 1)

array([[34, 43, 10, 73],
       [82, 22, 10, 12],
       [53, 94, 10, 66]])

In [165]:
np.insert(sampleArray,2,10, axis =0)

array([[34, 43, 73],
       [82, 22, 12],
       [10, 10, 10],
       [53, 94, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [195]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])


In [196]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [197]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [198]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [ ]:
OR

In [193]:
z=np.dot(x,y)
z

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [90]:
arr = np.random.randint(3,size=20)
arr



array([1, 1, 1, 1, 0, 0, 2, 0, 1, 1, 2, 0, 0, 1, 1, 2, 2, 2, 1, 2])

In [91]:
arr.cumsum()

array([ 1,  2,  3,  4,  4,  4,  6,  6,  7,  8, 10, 10, 10, 11, 12, 14, 16,
       18, 19, 21], dtype=int32)

In [ ]:
OR

In [188]:
z = np.random.randn(20)

In [189]:
z

array([ 0.284513  ,  0.10234155,  0.97514289,  0.9474708 , -0.38508808,
        0.71894724,  1.62762157,  0.93215214, -1.84333757,  0.09721851,
       -1.5075904 , -2.06408372,  0.60059125, -1.47525779,  1.03639752,
       -0.33713509, -0.21071618, -0.00611317,  1.07997523,  1.04752833])

In [190]:
z.cumsum()

array([ 0.284513  ,  0.38685455,  1.36199744,  2.30946824,  1.92438016,
        2.64332741,  4.27094898,  5.20310113,  3.35976355,  3.45698206,
        1.94939166, -0.11469206,  0.48589919, -0.9893586 ,  0.04703893,
       -0.29009617, -0.50081235, -0.50692552,  0.57304971,  1.62057804])